# **LIST**

## append()

### Syntax

```python
list.append(obj)
```

In [3]:
a = [1, 2, 3, 4]
a

[1, 2, 3, 4]

In [4]:
a.append([1, 9])
a

[1, 2, 3, 4, [1, 9]]

In [5]:
a.append("a_string")
a

[1, 2, 3, 4, [1, 9], 'a_string']

In [7]:
a.append(0.89)
a

[1, 2, 3, 4, [1, 9], 'a_string', 0.89]

In [8]:
a.append(0, 89)

TypeError: append() takes exactly one argument (2 given)

## extend()

### Syntax
```python
list.extend(sequence)
```

In [33]:
a = [1, 2, 3, 4, [1, 9], 'a_string', 0.89]
b = [2, 2, 2, 2, 3, 3]

a.extend(b)
print(a)
print(b)

[1, 2, 3, 4, [1, 9], 'a_string', 0.89, 2, 2, 2, 2, 3, 3]
[2, 2, 2, 2, 3, 3]


In [34]:
a = [1, 2, 3, 4, [1, 9], 'a_string', 0.89]
b = [2, 2, 2, 2, 3, 3]

b.extend(a)
print(a)
print(b)

[1, 2, 3, 4, [1, 9], 'a_string', 0.89]
[2, 2, 2, 2, 3, 3, 1, 2, 3, 4, [1, 9], 'a_string', 0.89]


## pop()

### Syntax

```python
list.pop(obj = list[-1])
```

In [1]:
a = [1, 2, 3, 4, [1, 9], 'a_string', 0.89]
a

[1, 2, 3, 4, [1, 9], 'a_string', 0.89]

In [2]:
a.pop()
a

[1, 2, 3, 4, [1, 9], 'a_string']

In [3]:
a.pop()
a

[1, 2, 3, 4, [1, 9]]

In [4]:
a.pop()
a

[1, 2, 3, 4]

In [5]:
a = a[:-1]
a

[1, 2, 3]

## remove()

### Syntax
```python
list.remove(obj)
```

In [22]:
a = [1, 2, 3, 4, [1, 9], 'a_string', 0.89]
a

[1, 2, 3, 4, [1, 9], 'a_string', 0.89]

In [23]:
a.remove(2)
a

[1, 3, 4, [1, 9], 'a_string', 0.89]

In [24]:
a.remove([1, 9])
a

[1, 3, 4, 'a_string', 0.89]

In [10]:
a.remove("a_string")
a

[1, 3, 4, 0.89]

In [69]:
a = [1, 2, 3, 4, [1, 9], 'a_string', 0.89]
b = [2, 2, 2, 2, 3, 3]

a.extend(b)
print(a)

while 2 in a:
    a.remove(2)
print(a)

[1, 2, 3, 4, [1, 9], 'a_string', 0.89, 2, 2, 2, 2, 3, 3]
[1, 3, 4, [1, 9], 'a_string', 0.89, 3, 3]


In [71]:
a = [1, 2, 3, 4, [1, 9], 'a_string', 0.89]
b = [2, 2, 2, 2, 3, 3]

a.extend(b)
print(a)

[value for value in a if value != 2]

[1, 2, 3, 4, [1, 9], 'a_string', 0.89, 2, 2, 2, 2, 3, 3]


[1, 3, 4, [1, 9], 'a_string', 0.89, 3, 3]

## del()

### Syntax
```python
del(obj)
```

In [25]:
a = [1, 2, 3, 4, [1, 9], 'a_string', 0.89]
a

[1, 2, 3, 4, [1, 9], 'a_string', 0.89]

In [26]:
del(a[2])
a

[1, 2, 4, [1, 9], 'a_string', 0.89]

In [18]:
del(a[4])
a

[1, 2, 4, [1, 9], 0.89]

In [19]:
del(a)
a

NameError: name 'a' is not defined

In [27]:
a = [1, 2, 3, 4, [1, 9], 'a_string', 0.89]
del(a[2:7:2])
a

[1, 2, 4, 'a_string']

## count()

### Syntax
```python
list.count(obj)
```

In [35]:
a = [1, 2, 3, 4, [1, 9], 'a_string', 0.89]
b = [2, 2, 2, 2, 3, 3]

a.extend(b)
a

[1, 2, 3, 4, [1, 9], 'a_string', 0.89, 2, 2, 2, 2, 3, 3]

In [36]:
a.count(2)

5

In [37]:
a.count(3)

3

In [38]:
a.count("a_string")

1

## index()

### Syntax
```python
list.index(obj)
```

In [42]:
a = [1, 2, 3, 4, [1, 9], 'a_string', 0.89]
b = [2, 2, 2, 2, 3, 3]

a.extend(b)
a

[1, 2, 3, 4, [1, 9], 'a_string', 0.89, 2, 2, 2, 2, 3, 3]

In [61]:
a.index([1, 9])

4

In [43]:
a.index(2)

1

In [52]:
for index, element in enumerate(a):
    print(index, element)

0 1
1 2
2 3
3 4
4 [1, 9]
5 a_string
6 0.89
7 2
8 2
9 2
10 2
11 3
12 3


In [57]:
for index, element in enumerate(a):
    if element == 2:
        print(index, end="\t")

1	7	8	9	10	

In [59]:
[index for index, element in enumerate(a) if element == 2]

[1, 7, 8, 9, 10]

In [60]:
index for index, element in enumerate(a) if element == 2

SyntaxError: invalid syntax (<ipython-input-60-c047d21c1472>, line 1)

## insert()

### Syntax
```python
list.insert(index, obj)
```

In [73]:
a = [1, 2, 3, 4, [1, 9], 'a_string', 0.89]
a

[1, 2, 3, 4, [1, 9], 'a_string', 0.89]

In [74]:
a.insert(3, 2001)
a

[1, 2, 3, 2001, 4, [1, 9], 'a_string', 0.89]

In [75]:
a.insert(7, 2001)
a

[1, 2, 3, 2001, 4, [1, 9], 'a_string', 2001, 0.89]

## sort()

### Syntax
```python
list.sort()
```

In [100]:
a = [3, 2, 1, 4, [1, 9], 'a_string', 0.89]
b = [2, 2, 2, 2, 3, 3]

a.extend(b)
a

[3, 2, 1, 4, [1, 9], 'a_string', 0.89, 2, 2, 2, 2, 3, 3]

In [101]:
a.sort()
a

TypeError: '<' not supported between instances of 'list' and 'int'

In [102]:
a[:3].sort()
a

[1, 2, 3, 4, [1, 9], 'a_string', 0.89, 2, 2, 2, 2, 3, 3]

## reverse()

### Syntax
```python
list.reverse()
```

In [86]:
a = [1, 2, 3, 4, [1, 9], 'a_string', 0.89]
b = [2, 2, 2, 2, 3, 3]

a.extend(b)
a

[1, 2, 3, 4, [1, 9], 'a_string', 0.89, 2, 2, 2, 2, 3, 3]

In [87]:
a.reverse()
a

[3, 3, 2, 2, 2, 2, 0.89, 'a_string', [1, 9], 4, 3, 2, 1]

## len()

### Syntax
```python
len(list)
```

In [88]:
a = [1, 2, 3, 4, [1, 9], 'a_string', 0.89]
len(a)

7

In [89]:
b = [2, 2, 2, 2, 3, 3]
len(b)

6

In [91]:
a = [1, 2, 3, 4, [1, 9], 'a_string', 0.89]
b = [2, 2, 2, 2, 3, 3]

a.extend(b)
len(a)

13

## max()

### Syntax
```python
max(list)
```

In [95]:
a = [1, 2, 3, 4, [1, 9], 'a_string', 0.89]
max(a)

TypeError: '>' not supported between instances of 'str' and 'int'

In [94]:
b = [2, 2, 2, 2, 3, 3]
max(b)

3

## min()

### Syntax
```python
min(list)
```

In [96]:
a = [1, 2, 3, 4, [1, 9], 'a_string', 0.89]
min(a)

TypeError: '<' not supported between instances of 'list' and 'int'

In [97]:
b = [2, 2, 2, 2, 3, 3]
min(b)

2

## Slicing

### Syntax
```python
a[low:high:step] if step>0
a[high:low:step] if step<0
```

In [131]:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
a

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

In [132]:
a[1:3]

[2, 3]

In [133]:
a[1:9:2]

[2, 4, 6, 8]

In [134]:
a[:9:2]

[1, 3, 5, 7, 9]

In [135]:
a[::2]

[1, 3, 5, 7, 9, 11]

In [136]:
a[:-2]

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [137]:
a[-2:]

[11, 12]

In [138]:
a[::-1]

[12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1]

In [143]:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
a[-3::-2]

[10, 8, 6, 4, 2]

In [142]:
a[:-5:-1]

[12, 11, 10, 9]

# **Mock Test**

### 1
$$ f(x) = 1 + \frac{1}{1 + e^{-x}} $$

In [2]:
import math

def func(number):
    return 1 + 1/(1 + math.pow(math.e, -number))

In [8]:
number = int(input('Enter the a number to activate above function: '))
print("f({}) = {}".format(number, func(number)))

Enter the a number to activate above function:  1


f(1) = 1.7310585786300048


In [7]:
number = int(input('Enter the a number to activate above function: '))
print("f({}) = {:.4f}".format(number, func(number)))

Enter the a number to activate above function:  1


f(1) = 1.7311


In [3]:
number = int(input('Enter the a number to activate above function: '))
print(f"f({number}) = {func(number):.8g}")

Enter the a number to activate above function:  1


f(1) = 1.7310586


In [ ]:
#include <stdio.h>
#include <math.h>

double compute_function (int x)
{
    double result = 1 + (1/(1 + exp(-x)));
    return result;
}

int main()
{
    int num1, num2;
    
    printf("Enter a number: \n>> ");
    scanf("%d",&num1);
    printf("f(%d) = %.8g\n\n", num1, compute_function(num1));
    
    printf("Enter a number: \n>> ");
    scanf("%d",&num2);
    printf("f(%d) = %.8g\n\n", num2, compute_function(num2));
}

$$ PI \approx 4\sum_{i=1}^{n}\frac{(-1)^{i+1}}{2i-1} $$

In [10]:
def estimate_pi(n=1000):
    pi = 0
    for i in range(1, n):
        pi += (-1)**(i+1) / (2*i - 1)
    return pi*4

print(f"pi = {estimate_pi():.6f}")

pi = 3.142594


In [ ]:
#include <stdio.h>
#include <math.h>

double estimate_pi(int n)
{
    if (n > 0)
        return pow(-1, n+1) / (2*n-1) + estimate_pi(n-1);
    else
        return  0;
}

int main()
{
    printf("\nPI is approximately %lf\n", 4*estimate_pi(1000));
}

### 2
$$ f(x_{i}) = \frac{e^{x_{i}}}{\sum_{j}e^{x_{j}}} $$

In [6]:
import math
import numpy as np

def softmax_1(array):
    denominator = 0
    for element in array:
        denominator += math.exp(element)
        
    print("denominator = ", denominator)
    
    result = []  
    for element in array:
        result.append(math.exp(element) / denominator)
                          
    return result

array = [1.0, 2.0, 3.0]
print("Softmax = ", softmax_1(array))
print("Softmax = ", np.around(softmax_1(array), 3))

denominator =  30.19287485057736
Softmax =  [0.09003057317038046, 0.24472847105479767, 0.6652409557748219]
denominator =  30.19287485057736
Softmax =  [0.09  0.245 0.665]


In [48]:
import numpy as np

def softmax_2(array):
    return np.exp(array) / sum(np.exp(array))

array = [1.0, 2.0, 3.0]
print(softmax_2(array))
print(np.around(softmax_2(array), 3))

[0.09003057 0.24472847 0.66524096]
[0.09  0.245 0.665]


In [66]:
from scipy.special import softmax

array = [1.0, 2.0, 3.0]
print(softmax(array))
print(np.around(softmax(array), 3))

[0.09003057 0.24472847 0.66524096]
[0.09  0.245 0.665]


In [ ]:
#include <stdio.h>
#include <stdlib.h>
#include <math.h>

#define length 3

void print_array(double array[])
{
    int i;
    
    for (i = 0; i < length; i++)
    {
        printf("%.3g\t", array[i]);
    }
    puts("");
}

void softmax(double array[])
{
    double denominator = 0;
    int i;
    double result[length];
    
    for(i = 0; i < length; i++)
    {
        denominator += exp(array[i]);
    }
    
    
    for(i = 0; i < length; i++)
    {
        result[i] = exp(array[i]) / denominator;
    }
    
    print_array(result);
}

int main()
{
    double array[length] = {1.0, 2.0, 3.0};
    
    printf("Your array:\n");
    print_array(array);
    printf("Softmax:\n");
    softmax(array);
}

In [ ]:
#include <stdio.h>
#include <stdlib.h>
#include <math.h>

double * softmax(double array[], int length)
{
    double denominator = 0;
    int i;
    double * result = (double*)malloc(length * sizeof(double));
    
    for(i = 0; i < length; i++)
    {
        denominator += exp(array[i]);
    }
    
    
    for(i = 0; i < length; i++)
    {
        result[i] = exp(array[i]) / denominator;
    }
    
    return result;
}

void print_array(double *array, int length)
{
    int i;
    
    for (i = 0; i < length; i++)
    {
        printf("%.3g\t", array[i]);
    }
    puts("");
}

int main()
{
    double array[] = {1.0, 2.0, 3.0};
    int length = (int)sizeof(array)/sizeof(array[0]);
    double * result = softmax(array, length);
    
    printf("Your array:\n");
    print_array(array, length);
    printf("Softmax:\n");
    print_array(result, length);
}

In [ ]:
#include <stdio.h>
#include <stdlib.h>
#include <math.h>

void print_array(double array[], int length)
{
    int i;
    
    for (i = 0; i < length; i++)
    {
        printf("%.3g\t", array[i]);
    }
    puts("");
}

void softmax(double array[], int length)
{
    double denominator = 0;
    int i;
    double result[length];
    
    for(i = 0; i < length; i++)
    {
        denominator += exp(array[i]);
    }
    
    for(i = 0; i < length; i++)
    {
        result[i] = exp(array[i]) / denominator;
    }
    
    print_array(result, length);
}

int main()
{
    double array[] = {1.0, 2.0, 3.0};
    int length = (int)sizeof(array)/sizeof(array[0]);
    
    printf("Your array:\n");
    print_array(array, length);
    printf("Softmax:\n");
    softmax(array, length);
}

### 3
a) Given a fixed n and an array with the size of n, write a function to set random integers in the interval [0, 9]  
b) Write a function to compute the sum of all the elements of the array.

In [68]:
import random

def random_array(n):
    array = []
    for i in range(n):
        array.append(random.randint(0,9))
    return array

def sum_array(array):
    result = 0
    for element in array:
        result += element
    return result

array = random_array(5)
print(array)
print("Sum of array =", sum_array(array))

[4, 7, 2, 7, 3]
Sum of array = 23


In [70]:
import random

def random_array(n):
    return [random.randint(0,9) for _ in range(n)]

def sum_array(array):
    result = 0
    for element in array:
        result += element
    return result

array = random_array(5)
print(array)
print("Sum of array =", sum_array(array))

[6, 5, 1, 1, 9]
Sum of array = 22


In [ ]:
#include <stdio.h>
#include <stdlib.h>
#include <time.h>

#define length 5

int main()
{
    int array[length];
    int i;
    int sum = 0;
    srand(time(NULL)); 
    
    for (i = 0; i < length; i++)
    {
        array[i] = rand() % 10;
        printf("%d\t", array[i]);
    }
    
    for (i = 0; i < length; i++)
    {
        sum += array[i];
    }
    
    printf("\nsum = %d", sum);
}


In [ ]:
#include <stdio.h>
#include <stdlib.h>
#include <time.h>

#define length 5

void print_array(int array[])
{
    int i;
    
    for (i = 0; i < length; i++)
    {
        printf("%d\t", array[i]);
    }
}

int sum_array(int array[])
{
    int sum = 0;
    int i;
    
    for (i = 0; i < length; i++)
    {
        sum += array[i];
    } 
    
    return sum;
}

int main()
{
    int array[length];
    int i;
    srand(time(NULL)); 
    
    for(i = 0; i < length; i++)
    {
        array[i] = rand() % 10;
    }
    
    printf("\nYour array: \n");
    print_array(array);
    printf("\nsum = %d", sum_array(array));
}

In [ ]:
#include <stdio.h>
#include <stdlib.h>
#include <time.h>

int random_array(int * array, int length)
{
    int i;
    srand(time(NULL));  
    
    for (i = 0; i < length; i++)
    {
        array[i] = rand() % 10;
    }
}

void print_array(int array[], int length)
{
    int i;
    
    for (i = 0; i < length; i++)
    {
        printf("%d\t", array[i]);
    }
}

int sum_array(int array[], int length)
{
    int sum = 0;
    int i;
    
    for (i = 0; i < length; i++)
    {
        sum += array[i];
    } 
    
    return sum;
}

int main()
{
    int length;
    int * array = (int*)malloc(length * sizeof(int));
    
    printf("Enter array's length: \n>> ");
    scanf("%d", &length);
    
    random_array(array, length);
    printf("\nYour array: \n");
    print_array(array, length);
    printf("\nsum = %d", sum_array(array, length));
}

In [ ]:
#include <stdio.h>
#include <stdlib.h>
#include <time.h>

void print_array(int array[], int length)
{
    int i;
    
    for (i = 0; i < length; i++)
    {
        printf("%d\t", array[i]);
    }
}

int sum_array(int array[], int length)
{
    int sum = 0;
    int i;
    
    for (i = 0; i < length; i++)
    {
        sum += array[i];
    } 
    
    return sum;
}

void random_array(int array[], int length)
{
    int i;
    srand(time(NULL));  
    
    for (i = 0; i < length; i++)
    {
        array[i] = rand() % 10;
    }
    
    print_array(array, length);
    printf("\nsum = %d", sum_array(array, length));
}

int main()
{
    int length;
    
    printf("Enter array's length: \n>> ");
    scanf("%d", &length);
    
    int array[length];
    
    random_array(array, length);
}